### ISSUE TITLE
Allow a 'default' role to be configured

### ISSUE THREAD

**Issue by jkueh** [jkueh/roo#3]
Suggestion came through to allow for a role to be flagged as the 'default' role so that we don't have to provide the `-role` flag each time, e.g.

```yaml
roles:
  - name: test
    default: true
    ...
```
